FROM php:8.3-apache
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN a2enmod rewrite
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
RUN                                                                            \
    set -eux;                                                                  \
    /bin/echo -e '#!/bin/sh\necho "$@"\nexec cat' > /usr/local/bin/echocat;    \
    chmod a+x /usr/local/bin/echocat;                                          \
    echo sendmail_path = /usr/local/bin/echocat                                \
        > "$PHP_INI_DIR/conf.d/sendmail_is_echocat.ini"
RUN                                                                            \
    set -eux;                                                                  \
    apt-get update;                                                            \
    apt-get install --assume-yes unzip;                                        \
    curl --remote-name http://yui.github.io/yui2/archives/yui_2.9.0.zip;       \
    unzip yui_2.9.0.zip -d /tmp;                                               \
    rm yui_2.9.0.zip;                                                          \
    mv /tmp/yui/build /var/www/html/yui;                                       \
    rm -r /tmp/yui;                                                            \
    apt-get purge --assume-yes unzip;                                          \
    apt-get clean;                                                             \
    rm -rf /var/lib/apt/lists/*
